# Generated by Django 2.2.6 on 2019-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterTest',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=64)),
                ('intername', models.CharField(max_length=64)),
                ('creatdate', models.CharField(max_length=32)),
                ('updatedate', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
