# Generated by Django 2.2.6 on 2019-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intertest',
            name='creatdate',
            field=models.DateTimeField(max_length=32),
        ),
        migrations.AlterField(
            model_name='intertest',
            name='updatedate',
            field=models.DateTimeField(max_length=32),
        ),
    ]
