# Generated by Django 2.2.6 on 2019-10-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inttest', '0002_auto_20191031_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intertest',
            name='creatdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intertest',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
