# Generated by Django 2.2.6 on 2020-01-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inttest', '0003_auto_20191031_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('displacement', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
