# Generated by Django 2.2.6 on 2020-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inttest', '0004_cars_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='intertest',
            name='params',
            field=models.FloatField(default='1', max_length=1000),
        ),
    ]
