# Generated by Django 2.2.6 on 2020-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inttest', '0005_intertest_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intertest',
            name='params',
            field=models.CharField(default='1', max_length=1000),
        ),
    ]
